/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0066cc',
        'primary-focus': '#0071e3',
        'primary-on-dark': '#2997ff',
        ink: '#1d1d1f',
        'ink-muted-80': '#333333',
        'ink-muted-48': '#7a7a7a',
        'body-muted': '#cccccc',
        'divider-soft': '#f0f0f0',
        hairline: '#e0e0e0',
        canvas: '#ffffff',
        'canvas-parchment': '#f5f5f7',
        'surface-pearl': '#fafafc',
        'surface-tile-1': '#272729',
        'surface-tile-2': '#2a2a2c',
        'surface-tile-3': '#252527',
        'surface-black': '#000000',
        'surface-chip-translucent': '#d2d2d7',
        'on-primary': '#ffffff',
        'on-dark': '#ffffff',
      },
      fontSize: {
        'hero-display': ['56px', { lineHeight: '1.07' }],
        'display-lg': ['40px', { lineHeight: '1.10' }],
        'display-md': ['34px', { lineHeight: '1.47' }],
        'lead': ['28px', { lineHeight: '1.14' }],
        'lead-airy': ['24px', { lineHeight: '1.5' }],
        'tagline': ['21px', { lineHeight: '1.19' }],
        'body-strong': ['17px', { lineHeight: '1.24' }],
        'body-base': ['17px', { lineHeight: '1.47' }],
        'dense-link': ['17px', { lineHeight: '2.41' }],
        'caption': ['14px', { lineHeight: '1.43' }],
        'caption-strong': ['14px', { lineHeight: '1.29' }],
        'button-large': ['18px', { lineHeight: '1.0' }],
        'button-utility': ['14px', { lineHeight: '1.29' }],
        'fine-print': ['12px', { lineHeight: '1.0' }],
        'nav-link': ['12px', { lineHeight: '1.0' }],
      },
      borderRadius: {
        'none': '0px',
        'xs': '5px',
        'sm': '8px',
        'md': '11px',
        'lg': '18px',
        'pill': '9999px',
      },
      spacing: {
        'z-xxs': '4px',
        'z-xs': '8px',
        'z-sm': '12px',
        'z-md': '17px',
        'z-lg': '24px',
        'z-xl': '32px',
        'z-xxl': '48px',
        'z-section': '80px',
      },
      fontFamily: {
        'display': ['SF Pro Display', 'system-ui', '-apple-system', 'sans-serif'],
        'text': ['SF Pro Text', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
